// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class AcceptedExamUniversityMap
    {
        [Key]
        public int Id { get; set; }
        public int? UniversityId { get; set; }
        public int? ExamId { get; set; }
        [StringLength(4)]
        public string YearAccepte { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey(nameof(ExamId))]
        [InverseProperty(nameof(AcceptedExam.AcceptedExamUniversityMap))]
        public virtual AcceptedExam Exam { get; set; }
        [ForeignKey(nameof(UniversityId))]
        [InverseProperty("AcceptedExamUniversityMap")]
        public virtual University University { get; set; }
    }
}