// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class AcceptedExam
    {
        public AcceptedExam()
        {
            AcceptedExamUniversityMap = new HashSet<AcceptedExamUniversityMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(4)]
        public string YearAccepte { get; set; }

        [InverseProperty("Exam")]
        public virtual ICollection<AcceptedExamUniversityMap> AcceptedExamUniversityMap { get; set; }
    }
}