// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class ArticalTagMap
    {
        [Key]
        public int Id { get; set; }
        public int? ArticalId { get; set; }
        public int? TagId { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey(nameof(ArticalId))]
        [InverseProperty("ArticalTagMap")]
        public virtual Artical Artical { get; set; }
        [ForeignKey(nameof(TagId))]
        [InverseProperty("ArticalTagMap")]
        public virtual Tag Tag { get; set; }
    }
}