// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Artical
    {
        public Artical()
        {
            ArticalTagMap = new HashSet<ArticalTagMap>();
            Comment = new HashSet<Comment>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        public string Title { get; set; }
        public string ArticalContent { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [StringLength(50)]
        public string Image { get; set; }
        [StringLength(250)]
        public string Link { get; set; }
        public int? NumberLike { get; set; }
        public int? Seen { get; set; }
        public int? UserId { get; set; }
        public int? CategoryId { get; set; }
        public int? LanguageId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("Artical")]
        public virtual Category Category { get; set; }
        [ForeignKey(nameof(LanguageId))]
        [InverseProperty("Artical")]
        public virtual Language Language { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Artical")]
        public virtual User User { get; set; }
        [InverseProperty("Artical")]
        public virtual ICollection<ArticalTagMap> ArticalTagMap { get; set; }
        [InverseProperty("Artical")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}