// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Certifica
    {
        public Certifica()
        {
            CvCertificaMap = new HashSet<CvCertificaMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(15)]
        public string Degree { get; set; }
        [StringLength(75)]
        public string SchoolName { get; set; }
        [StringLength(150)]
        public string Department { get; set; }
        [StringLength(4)]
        public string StartYear { get; set; }
        [StringLength(4)]
        public string EndYear { get; set; }
        [StringLength(5)]
        public string GraduateGrade { get; set; }

        [InverseProperty("Certifica")]
        public virtual ICollection<CvCertificaMap> CvCertificaMap { get; set; }
    }
}