// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class City
    {
        public City()
        {
            University = new HashSet<University>();
            User = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        public short CityCode { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("City")]
        public virtual ICollection<University> University { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<User> User { get; set; }
    }
}