// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class College
    {
        public College()
        {
            LanguageCollegeMap = new HashSet<LanguageCollegeMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Link { get; set; }
        public string About { get; set; }
        [StringLength(20)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Mail { get; set; }
        public int? StudingYear { get; set; }
        public int? FacultyId { get; set; }
        public int? DegreeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(DegreeId))]
        [InverseProperty(nameof(StudingDegree.College))]
        public virtual StudingDegree Degree { get; set; }
        [ForeignKey(nameof(FacultyId))]
        [InverseProperty("College")]
        public virtual Faculty Faculty { get; set; }
        [InverseProperty("College")]
        public virtual ICollection<LanguageCollegeMap> LanguageCollegeMap { get; set; }
    }
}