// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    [Table("CV")]
    public partial class Cv
    {
        public Cv()
        {
            CvCertificaMap = new HashSet<CvCertificaMap>();
            CvExperienceMap = new HashSet<CvExperienceMap>();
            CvLanguageMap = new HashSet<CvLanguageMap>();
            CvProjectMap = new HashSet<CvProjectMap>();
            CvReferenceMap = new HashSet<CvReferenceMap>();
            CvTalentMap = new HashSet<CvTalentMap>();
        }

        [Key]
        public int Id { get; set; }
        [Column("isMarried")]
        public bool? IsMarried { get; set; }
        public string About { get; set; }
        public string CareerDestination { get; set; }
        [StringLength(20)]
        public string Image { get; set; }
        [Column("isDoneMilitary")]
        public bool? IsDoneMilitary { get; set; }
        public int? UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Cv")]
        public virtual User User { get; set; }
        [InverseProperty("Cv")]
        public virtual ICollection<CvCertificaMap> CvCertificaMap { get; set; }
        [InverseProperty("Cv")]
        public virtual ICollection<CvExperienceMap> CvExperienceMap { get; set; }
        [InverseProperty("Cv")]
        public virtual ICollection<CvLanguageMap> CvLanguageMap { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<CvProjectMap> CvProjectMap { get; set; }
        [InverseProperty("Cv")]
        public virtual ICollection<CvReferenceMap> CvReferenceMap { get; set; }
        [InverseProperty("Cv")]
        public virtual ICollection<CvTalentMap> CvTalentMap { get; set; }
    }
}