// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class CvCertificaMap
    {
        [Key]
        public int Id { get; set; }
        public int? CvId { get; set; }
        public int? CertificaId { get; set; }

        [ForeignKey(nameof(CertificaId))]
        [InverseProperty("CvCertificaMap")]
        public virtual Certifica Certifica { get; set; }
        [ForeignKey(nameof(CvId))]
        [InverseProperty("CvCertificaMap")]
        public virtual Cv Cv { get; set; }
    }
}