// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class CvExperienceMap
    {
        [Key]
        public int Id { get; set; }
        public int? CvId { get; set; }
        public int? ExperienceId { get; set; }

        [ForeignKey(nameof(CvId))]
        [InverseProperty("CvExperienceMap")]
        public virtual Cv Cv { get; set; }
        [ForeignKey(nameof(ExperienceId))]
        [InverseProperty("CvExperienceMap")]
        public virtual Experience Experience { get; set; }
    }
}