// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class CvLanguageMap
    {
        [Key]
        public int Id { get; set; }
        public int? CvId { get; set; }
        public int? LanguageId { get; set; }
        [StringLength(4)]
        public string Rate { get; set; }

        [ForeignKey(nameof(CvId))]
        [InverseProperty("CvLanguageMap")]
        public virtual Cv Cv { get; set; }
        [ForeignKey(nameof(LanguageId))]
        [InverseProperty("CvLanguageMap")]
        public virtual Language Language { get; set; }
    }
}