// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class CvProjectMap
    {
        [Key]
        public int Id { get; set; }
        public int? CvId { get; set; }
        public int? ProjectId { get; set; }

        [ForeignKey(nameof(ProjectId))]
        [InverseProperty(nameof(Cv.CvProjectMap))]
        public virtual Cv Project { get; set; }
        [ForeignKey(nameof(ProjectId))]
        [InverseProperty("CvProjectMap")]
        public virtual Project ProjectNavigation { get; set; }
    }
}