// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class ExamLanguageMap
    {
        [Key]
        public int Id { get; set; }
        public int? LanguageId { get; set; }
        public int? ExamId { get; set; }

        [ForeignKey(nameof(LanguageId))]
        [InverseProperty(nameof(ExamUniversity.ExamLanguageMap))]
        public virtual ExamUniversity Language { get; set; }
        [ForeignKey(nameof(LanguageId))]
        [InverseProperty("ExamLanguageMap")]
        public virtual Language LanguageNavigation { get; set; }
    }
}