// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Experience
    {
        public Experience()
        {
            CvExperienceMap = new HashSet<CvExperienceMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string NameCompany { get; set; }
        [StringLength(50)]
        public string EmailCompany { get; set; }
        [StringLength(150)]
        public string Department { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }

        [InverseProperty("Experience")]
        public virtual ICollection<CvExperienceMap> CvExperienceMap { get; set; }
    }
}