// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Language
    {
        public Language()
        {
            Artical = new HashSet<Artical>();
            CvLanguageMap = new HashSet<CvLanguageMap>();
            ExamLanguageMap = new HashSet<ExamLanguageMap>();
            LanguageCollegeMap = new HashSet<LanguageCollegeMap>();
            LnaguageUniversityMap = new HashSet<LnaguageUniversityMap>();
            News = new HashSet<News>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string Name { get; set; }

        [InverseProperty("Language")]
        public virtual ICollection<Artical> Artical { get; set; }
        [InverseProperty("Language")]
        public virtual ICollection<CvLanguageMap> CvLanguageMap { get; set; }
        [InverseProperty("LanguageNavigation")]
        public virtual ICollection<ExamLanguageMap> ExamLanguageMap { get; set; }
        [InverseProperty("Language")]
        public virtual ICollection<LanguageCollegeMap> LanguageCollegeMap { get; set; }
        [InverseProperty("Language")]
        public virtual ICollection<LnaguageUniversityMap> LnaguageUniversityMap { get; set; }
        [InverseProperty("Language")]
        public virtual ICollection<News> News { get; set; }
    }
}