// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class LanguageCollegeMap
    {
        [Key]
        public int Id { get; set; }
        [StringLength(3)]
        public string Rate { get; set; }
        public int? CollegeId { get; set; }
        public int? LanguageId { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey(nameof(CollegeId))]
        [InverseProperty("LanguageCollegeMap")]
        public virtual College College { get; set; }
        [ForeignKey(nameof(LanguageId))]
        [InverseProperty("LanguageCollegeMap")]
        public virtual Language Language { get; set; }
    }
}