// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class LnaguageUniversityMap
    {
        [Key]
        public int Id { get; set; }
        public int? UnivId { get; set; }
        public int? LanguageId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(LanguageId))]
        [InverseProperty("LnaguageUniversityMap")]
        public virtual Language Language { get; set; }
        [ForeignKey(nameof(UnivId))]
        [InverseProperty(nameof(University.LnaguageUniversityMap))]
        public virtual University Univ { get; set; }
    }
}