// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Message
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        public string MessageContent { get; set; }
        public int? SenderUser { get; set; }
        public int? SendToUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendDate { get; set; }
        [Column("isSeeing")]
        public bool? IsSeeing { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SeeingDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey(nameof(SendToUser))]
        [InverseProperty(nameof(User.MessageSendToUserNavigation))]
        public virtual User SendToUserNavigation { get; set; }
        [ForeignKey(nameof(SenderUser))]
        [InverseProperty(nameof(User.MessageSenderUserNavigation))]
        public virtual User SenderUserNavigation { get; set; }
    }
}