// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class NewsTagMap
    {
        [Key]
        public int Id { get; set; }
        public int? NewsId { get; set; }
        public int? TagId { get; set; }

        [ForeignKey(nameof(NewsId))]
        [InverseProperty("NewsTagMap")]
        public virtual News News { get; set; }
        [ForeignKey(nameof(TagId))]
        [InverseProperty("NewsTagMap")]
        public virtual Tag Tag { get; set; }
    }
}