// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Project
    {
        public Project()
        {
            CvProjectMap = new HashSet<CvProjectMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        public string About { get; set; }
        [StringLength(150)]
        public string Place { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Column("isGorup")]
        public bool? IsGorup { get; set; }

        [InverseProperty("ProjectNavigation")]
        public virtual ICollection<CvProjectMap> CvProjectMap { get; set; }
    }
}