// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Reference
    {
        public Reference()
        {
            CvReferenceMap = new HashSet<CvReferenceMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(15)]
        public string Number { get; set; }

        [InverseProperty("Reference")]
        public virtual ICollection<CvReferenceMap> CvReferenceMap { get; set; }
    }
}