// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Role
    {
        public Role()
        {
            RoleTaskMap = new HashSet<RoleTaskMap>();
            UserRoleMap = new HashSet<UserRoleMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(10)]
        public string RoleName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }

        [InverseProperty("Role")]
        public virtual ICollection<RoleTaskMap> RoleTaskMap { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<UserRoleMap> UserRoleMap { get; set; }
    }
}