// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class RoleTaskMap
    {
        [Key]
        public int Id { get; set; }
        public int? RoleId { get; set; }
        public int? TaskId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty("RoleTaskMap")]
        public virtual Role Role { get; set; }
        [ForeignKey(nameof(TaskId))]
        [InverseProperty("RoleTaskMap")]
        public virtual Task Task { get; set; }
    }
}