// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class RoomMessages
    {
        [Key]
        public int Id { get; set; }
        public string MessageContent { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendeDate { get; set; }
        public int? MemberId { get; set; }
        public int? TeamRoomId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }

        [ForeignKey(nameof(MemberId))]
        [InverseProperty(nameof(TeamMemberMap.RoomMessages))]
        public virtual TeamMemberMap Member { get; set; }
        [ForeignKey(nameof(TeamRoomId))]
        [InverseProperty("RoomMessages")]
        public virtual TeamRoom TeamRoom { get; set; }
    }
}