// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Tag
    {
        public Tag()
        {
            ArticalTagMap = new HashSet<ArticalTagMap>();
            NewsTagMap = new HashSet<NewsTagMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }

        [InverseProperty("Tag")]
        public virtual ICollection<ArticalTagMap> ArticalTagMap { get; set; }
        [InverseProperty("Tag")]
        public virtual ICollection<NewsTagMap> NewsTagMap { get; set; }
    }
}