// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Talent
    {
        public Talent()
        {
            CvTalentMap = new HashSet<CvTalentMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string TalentName { get; set; }
        [StringLength(4)]
        public string Rate { get; set; }

        [InverseProperty("Talent")]
        public virtual ICollection<CvTalentMap> CvTalentMap { get; set; }
    }
}