// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Task
    {
        public Task()
        {
            RoleTaskMap = new HashSet<RoleTaskMap>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string TaskName { get; set; }

        [InverseProperty("Task")]
        public virtual ICollection<RoleTaskMap> RoleTaskMap { get; set; }
    }
}