// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class Team
    {
        public Team()
        {
            TeamMemberMap = new HashSet<TeamMemberMap>();
            TeamRoom = new HashSet<TeamRoom>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Conspet { get; set; }
        public int? LeaderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }

        [ForeignKey(nameof(LeaderId))]
        [InverseProperty("Team")]
        public virtual TeamMemberMap Leader { get; set; }
        [InverseProperty("TeamNavigation")]
        public virtual ICollection<TeamMemberMap> TeamMemberMap { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<TeamRoom> TeamRoom { get; set; }
    }
}