// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class TeamMemberMap
    {
        public TeamMemberMap()
        {
            RoomMessages = new HashSet<RoomMessages>();
            Team = new HashSet<Team>();
        }

        [Key]
        public int Id { get; set; }
        public int? UserId { get; set; }
        public int? TeamId { get; set; }
        [StringLength(30)]
        public string Position { get; set; }
        [StringLength(20)]
        public string NickName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpadatDate { get; set; }
        public string Description { get; set; }

        [ForeignKey(nameof(TeamId))]
        [InverseProperty("TeamMemberMap")]
        public virtual Team TeamNavigation { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("TeamMemberMap")]
        public virtual User User { get; set; }
        [InverseProperty("Member")]
        public virtual ICollection<RoomMessages> RoomMessages { get; set; }
        [InverseProperty("Leader")]
        public virtual ICollection<Team> Team { get; set; }
    }
}