// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Core.Models
{
    public partial class UniversityGalery
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(70)]
        public string Link { get; set; }
        [Column("isVideo")]
        public bool? IsVideo { get; set; }
        public int? UinversityId { get; set; }


        [ForeignKey(nameof(UinversityId))]
        [InverseProperty(nameof(University.UniversityGalery))]
        public virtual University Uinversity { get; set; }
    }
}